version: '2'
services:
    autodiscovery:
        build: ./autodiscovery/
        mem_limit: 128m
        expose:
            - 53
            - 8300
            - 8301
            - 8302
            - 8400
            - 8500
        ports:
            - 8500:8500
        dns:
            - 127.0.0.1

    ##
    # Battle Microservice
    ##
    microservice_battle_fpm:
        build: ./microservices/battle/php-fpm/
        working_dir: /var/www/html
        volumes_from:
            - source_battle
        links:
            - autodiscovery
            - microservice_user_nginx
        expose:
            - 9000
        environment:
            - BACKEND=microservice-battle-nginx
            - CONSUL=autodiscovery

    microservice_battle_nginx:
        build: ./microservices/battle/nginx/
        volumes_from:
            - source_battle
        links:
            - autodiscovery
            - microservice_battle_fpm
        environment:
            - BACKEND=microservice-battle-fpm
            - CONSUL=autodiscovery
        ports:
            - 8081:80
            - 9091:9090

    source_battle:
        image: nginx:stable
        volumes:
            - ./source/battle:/var/www/html
        command: "true"

    ##
    # User Microservice
    ##
    microservice_user_fpm:
        build: ./microservices/user/php-fpm/
        working_dir: /var/www/html
        volumes_from:
            - source_user
        links:
            - autodiscovery
        expose:
            - 9000
        environment:
            - BACKEND=microservice-user-nginx
            - CONSUL=autodiscovery

    microservice_user_nginx:
        build: ./microservices/user/nginx/
        volumes_from:
            - source_user
        links:
            - autodiscovery
            - microservice_user_fpm
        environment:
            - BACKEND=microservice-user-fpm
            - CONSUL=autodiscovery
        ports:
            - 8082:80
            - 9092:9090

    source_user:
        image: nginx:stable
        volumes:
            - ./source/user:/var/www/html
        command: "true"